# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_calendar_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellopluginsetting',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='reserve_calendar_date_hellopluginsetting', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='reservecalendartimepluginsetting',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='reserve_calendar_date_reservecalendartimepluginsetting', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
