# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='reserv_calendar_date_hellopluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('welcome', models.CharField(blank=True, max_length=128, null=True, verbose_name='Приветсвие')),
                ('afterword', models.TextField(blank=True, max_length=256, null=True, verbose_name='Послесовие')),
                ('unnamed_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя неавторизованного')),
                ('tag_class', models.CharField(blank=True, max_length=256, null=True, verbose_name='HTML класс')),
                ('tag_style', models.CharField(blank=True, max_length=256, null=True, verbose_name='HTML стиль')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
