# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 18:34
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('reserv_calendar_date', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv_Calendar_Time_PluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='reserv_calendar_date_reserv_calendar_time_pluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('num_of_month', models.IntegerField(blank=True, default=3, max_length=2, null=True, verbose_name='Number of months together')),
                ('show_weeks_number', models.BooleanField(default=False, verbose_name='Show number of weeks')),
                ('show_year', models.BooleanField(default=True, verbose_name='Show year')),
                ('mark_today', models.BooleanField(default=True, verbose_name='Mark today')),
                ('today_color', colorfield.fields.ColorField(blank=True, default='#FFC274', max_length=18, null=True, verbose_name='Color today cell')),
                ('busy_time_color', colorfield.fields.ColorField(blank=True, default='#E98282', max_length=18, null=True, verbose_name='Color busy time sell')),
                ('free_time_color', colorfield.fields.ColorField(blank=True, default='#89E6A3', max_length=18, null=True, verbose_name='Color free time sell')),
                ('tag_class', models.CharField(blank=True, max_length=256, null=True, verbose_name='HTML class')),
                ('tag_style', models.CharField(blank=True, max_length=256, null=True, verbose_name='HTML style')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
