# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0002_reserv_calendar_time_pluginsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='num_of_month',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Number of months together'),
        ),
    ]
