# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 19:36
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0003_auto_20180904_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserv_calendar_time_pluginsetting',
            name='mark_today',
        ),
        migrations.RemoveField(
            model_name='reserv_calendar_time_pluginsetting',
            name='today_color',
        ),
        migrations.AlterField(
            model_name='hellopluginsetting',
            name='afterword',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Afterword'),
        ),
        migrations.AlterField(
            model_name='hellopluginsetting',
            name='tag_class',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='HTML class'),
        ),
        migrations.AlterField(
            model_name='hellopluginsetting',
            name='tag_style',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='HTML class'),
        ),
        migrations.AlterField(
            model_name='hellopluginsetting',
            name='unnamed_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name of visitor'),
        ),
        migrations.AlterField(
            model_name='hellopluginsetting',
            name='welcome',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Welcome'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='busy_time_color',
            field=colorfield.fields.ColorField(blank=True, default='#dc3545', max_length=18, null=True, verbose_name='Color busy time sell'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='free_time_color',
            field=colorfield.fields.ColorField(blank=True, default='#28a745', max_length=18, null=True, verbose_name='Color free time sell'),
        ),
    ]
