# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0004_auto_20180904_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='tag_class',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='HTML class'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='tag_style',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='HTML style'),
        ),
    ]
