# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserv_calendar_date', '0005_auto_20180906_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('product', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Product')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=64, verbose_name='Price')),
                ('comment', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserv_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('master', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserv_master', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
