# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0007_reservation_delta_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='delta_time',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Delta time'),
        ),
    ]
