# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0008_auto_20180909_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='delta_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_time',
            field=models.DurationField(blank=True, default=None, help_text='Field with auto filling', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(help_text='End time for the reservation', verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(help_text='Start time for the reservation', verbose_name='Start time'),
        ),
    ]
