# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0009_auto_20180909_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserv_master', to=settings.AUTH_USER_MODEL, verbose_name='Master'),
            preserve_default=False,
        ),
    ]
