# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0010_auto_20180909_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv_calendar_time_pluginsetting',
            name='time_delta',
            field=models.DurationField(choices=[(datetime.timedelta(0, 1800), '30 m'), (datetime.timedelta(0, 3600), '1 h')], default=datetime.timedelta(0, 3600), verbose_name='Time Delta'),
        ),
    ]
