# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0011_reserv_calendar_time_pluginsetting_time_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv_calendar_time_pluginsetting',
            name='end_time',
            field=models.TimeField(default='17:00:00', verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='reserv_calendar_time_pluginsetting',
            name='start_time',
            field=models.TimeField(default='8:00:00', verbose_name='Start time'),
        ),
    ]
