# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0012_auto_20180914_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv_calendar_time_pluginsetting',
            name='text_before_calendars',
            field=models.TextField(blank=True, default='1. Select a free day of the month', null=True, verbose_name='Text before calendars'),
        ),
        migrations.AddField(
            model_name='reserv_calendar_time_pluginsetting',
            name='text_before_time_intervals',
            field=models.TextField(blank=True, default='2. Choose your free time', null=True, verbose_name='Text before time intervals'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='num_of_month',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Number of months to show'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='time_delta',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 2700), '45 minutes'), (datetime.timedelta(0, 3600), '1 hour'), (datetime.timedelta(0, 7200), '2 hours'), (datetime.timedelta(0, 10800), '3 hours'), (datetime.timedelta(0, 14400), '4 hours'), (datetime.timedelta(0, 18000), '5 hours'), (datetime.timedelta(0, 21600), '6 hours'), (datetime.timedelta(0, 25200), '7 hours'), (datetime.timedelta(0, 28800), '8 hours'), (datetime.timedelta(0, 32400), '9 hours'), (datetime.timedelta(0, 36000), '10 hours')], default=datetime.timedelta(0, 3600), verbose_name='Time Delta'),
        ),
    ]
