# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_calendar_date', '0013_auto_20180915_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv_calendar_time_pluginsetting',
            name='text_style',
            field=models.CharField(blank=True, default='margin: 1em;', max_length=256, null=True, verbose_name='HTML text style'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='text_before_calendars',
            field=models.CharField(blank=True, default='1. Select a free day of the month', max_length=256, null=True, verbose_name='Text before calendars'),
        ),
        migrations.AlterField(
            model_name='reserv_calendar_time_pluginsetting',
            name='text_before_time_intervals',
            field=models.CharField(blank=True, default='2. Choose your free time', max_length=256, null=True, verbose_name='Text before time intervals'),
        ),
    ]
