# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180909_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weekend_days',
            field=models.CharField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=None, max_length=1, null=True, verbose_name='Days of weekend'),
        ),
    ]
