# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 19:39
from __future__ import unicode_literals

from django.db import migrations
import weekday_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_weekend_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='weekend_days',
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekdays',
            field=weekday_field.fields.WeekdayField(blank=True, default=None, max_length=14, null=True, verbose_name='Weekdays'),
        ),
    ]
